spring:
  jpa:
    show-sql: true
    database: mysql
    hibernate.ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:

      naming:
          #physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
          #指定jpa的自动表生成策略，驼峰自动映射为下划线格式
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/blogs?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
      #自己的连接池配置
    hikari:
      pool-name: user-1
      minimum-idle: 30
      maximum-pool-size: 30
      connectionTimeout: 60000
      idleTimeout: 60000
      validationTimeout: 3000
      maxLifetime: 60000
      register-mbeans: true

hibernate:
  current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext


server:
  port: 8779
